### ISSUE TITLE
typo in install instructions

### ISSUE THREAD

**Issue by hugocoolens** [LeFroid/Viper-Browser#12]
cd viper-browser && mkdir build && cd build
should be:
cd Viper-Browser && mkdir build && cd build

but I personally would prefer viperbrowser as the directory name

**Comment by LeFroid** [comment]
Thank you for the suggestion. I will update the instructions to read
`
git clone https://github.com/LeFroid/Viper-Browser.git viper-browser
mkdir -p viper-browser/build && cd viper-browser/build
`
