### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by anarchotaoist** [LeFroid/Viper-Browser#14]
There is no video media playback available in various platforms 
e.g  no video playback in Odysee.com nor Twitter. 

nb Cannot login to Youtube.com  account either.

**Comment by LeFroid** [comment]
What operating system are you using?
What version of Qt and Qt WebEngine is being used on the host OS?

Have you tried changing the default user agent?
Not so sure about Twitter, but I believe that Google/Youtube blocks certain UAs such as QtWebEngine. This works for me, FWIW:

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.144 Safari/537.36

The user agent can be set to the above value, or anything else, from the Tools -> User Agents menu

**Comment by anarchotaoist** [comment]
Hello,
Thanks for the reply and suggestion.
I implemented the User Agent (I think - see attached pic) but it does not seem to make any difference.
![viper](https://user-images.githubusercontent.com/29670892/104971439-b2ad8b00-59e6-11eb-92d4-0ab76bd341d5.png)


Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2
Kernel Version: 5.8.0-38-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

**Comment by LeFroid** [comment]
Sorry for the delayed response. Have you activated the user agent after registering it with the web browser? Like so:
![image](https://user-images.githubusercontent.com/2191538/107121699-e9e2bf80-6861-11eb-8cca-b730f5ad8b35.png)

**Comment by LeFroid** [comment]
Closing- if you still have an issue after enabling the user agent (see above), please contact me.
