### ISSUE TITLE
[Feature Request] armv7hl and aarch64 support

### ISSUE THREAD

**Issue by stormchaser3000** [LeFroid/Viper-Browser#17]
Hello,

I wish I could help with this, but my knowlege of the low-level aspects of programming is still quite limited. I was hoping to bring up the issue of ARM support becaise I would love to use this on my Raspberry Pi 4 (which I currently run Slackware on). Firefox is a slow, unoptimized mess, and otter browser still uses QtWebkit, although it is the only one fast enough to be usable for me on this device at the moment.

Currently, I am getting errors relating to the sse instruction sets not existing on the Raspberry Pi 4's ARM processor. What would it take to add some code for the ARM neon extension? (basically ARM's equivilant of the x86 sse extensions if I understand correctly)

I may not be able to help much, but I would be willing to be a tester.

**Comment by LeFroid** [comment]
Hello,

I have just pushed a change such that SSE will only be enabled on x86 architectures. Can you please try a fresh build (delete any CMake artifacts like build directory, cache, etc. first) and let me know if you encounter any issues?

**Comment by stormchaser3000** [comment]
Thank you very much. It works like a charm on my Pinebook Pro, however, it appears that due to a bug in the version of qtwebengine I have installed on my Raspberry Pi (the bug came from upstream Chromium), I am unable to run this web browser  when using newer versions of glibc. This, however, is not the fault of Viper-Browser as best I can tell.
