### ISSUE TITLE
[MacOS] CMake does not find Qt installation

### ISSUE THREAD

**Issue by MahdiyarTH** [LeFroid/Viper-Browser#3]
i'm new in QT and clone your project, after cloning i opened terminal and went to project directory using cd command, after that i run "mkdir build && cd build" and after that "cmake .." and when i run make, it shows me an error "make: *** No targets specified and no makefile found.  Stop."
I'm using MacOS Mojave

**Comment by mahdiyarth** [comment]
Yes, it is my output. And i think is good to know that i'm really new in QT and don't know any thing yet, and event don't know how to work with CMake, i just followed the instructions.

-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.9.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/mahdiyartaheri/Qt5.7.0/Projects/Viper-Browser/build/CMakeFiles/CMakeOutput.log".

**Comment by LeFroid** [comment]
I see that you’re using Qt version 5.7
Please install version 5.9 or more recent (preferably 5.12), and run ‘cmake -DQt5_DIR=(path to QT installation)/lib/cmake/Qt5 ..’ from the build directory.

Please let me know if you encounter any further errors, this project should work on MacOS but I do not have a Mac to test with myself.

**Comment by mahdiyarth** [comment]
unfortunately i have to use QT 5.7 and i have not allowed to change QT version. Is there any other open source web browser that would be compatible with QT 5.7? I searched a lot in github but did not find any thing useful.

**Comment by LeFroid** [comment]
I'm not aware of any browsers that still support QT 5.7, other than QT's example browsers. You can try to compile viper-browser, and as long as it compiles it will work. You would have to change this line in the CMakeLists.txt:
    set(QT_VERSION_MIN "5.9.0")
to "5.7.0".

Otherwise I would suggest that you clone http://code.qt.io/cgit/qt/qtwebengine.git/tree/?h=5.7  and build the example browsers.

**Comment by mahdiyarth** [comment]
I changed the line that you said, but nothing changed. 
I just changed the line and run 'make' again and i got same error.

**Comment by LeFroid** [comment]
Did you also configure cmake with the Qt5 directory?
It would be something like 
  cmake -DQt5_DIR=(path to QT installation)/lib/cmake/Qt5 ..
Where you would first need to find the path to this “lib/cmake/Qt5” directory in your Qt installation.

**Comment by LeFroid** [comment]
If you installed Qt using brew, the cmake argument would be
-DQt5_DIR=$(brew --prefix qt)/lib/cmake/Qt5

**Comment by MahdiyarTH** [comment]
I gave that address to cmake command and it worked perfectly. But by running 'make' command i got a new error.


Scanning dependencies of target viper-core_autogen
[  1%] Automatic MOC and UIC for target viper-core
[  1%] Built target viper-core_autogen
Scanning dependencies of target viper-core
[  1%] Building CXX object src/core/CMakeFiles/viper-core.dir/adblock/AdBlockFilter.cpp.o
[  2%] Building CXX object src/core/CMakeFiles/viper-core.dir/adblock/AdBlockFilterParser.cpp.o
[  3%] Building CXX object src/core/CMakeFiles/viper-core.dir/adblock/AdBlockLog.cpp.o
[  3%] Building CXX object src/core/CMakeFiles/viper-core.dir/adblock/AdBlockLogTableModel.cpp.o
[  4%] Building CXX object src/core/CMakeFiles/viper-core.dir/adblock/AdBlockManager.cpp.o
/Users/mahdiyartaheri/Qt5.7.0/Projects/Viper-Browser/src/core/adblock/AdBlockManager.cpp:576:34: error: implicit instantiation of undefined template 'std::__1::array<QString, 4>'
    const std::array<QString, 4> whitelistedSchemes {
                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tuple:223:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
/Users/mahdiyartaheri/Qt5.7.0/Projects/Viper-Browser/src/core/adblock/AdBlockManager.cpp:785:71: error: no member named 'fromSecsSinceEpoch' in 'QDateTime'; did you mean 'fromMSecsSinceEpoch'?
        QDateTime lastUpdate = (ok && lastUpdateUInt > 0 ? QDateTime::fromSecsSinceEpoch(lastUpdateUInt) : QDateTime::currentDateTime());
                                                           ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
                                                                      fromMSecsSinceEpoch
/Users/mahdiyartaheri/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h:317:22: note: 'fromMSecsSinceEpoch' declared here
    static QDateTime fromMSecsSinceEpoch(qint64 msecs);
                     ^
/Users/mahdiyartaheri/Qt5.7.0/Projects/Viper-Browser/src/core/adblock/AdBlockManager.cpp:792:47: error: no member named 'fromSecsSinceEpoch' in 'QDateTime'; did you mean 'fromMSecsSinceEpoch'?
            QDateTime nextUpdate = QDateTime::fromSecsSinceEpoch(nextUpdateUInt);
                                   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
                                              fromMSecsSinceEpoch
/Users/mahdiyartaheri/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h:317:22: note: 'fromMSecsSinceEpoch' declared here
    static QDateTime fromMSecsSinceEpoch(qint64 msecs);
                     ^
/Users/mahdiyartaheri/Qt5.7.0/Projects/Viper-Browser/src/core/adblock/AdBlockManager.cpp:1017:115: error: no member named 'toSecsSinceEpoch' in 'QDateTime'; did you mean 'toMSecsSinceEpoch'?
        subscriptionObj.insert(QLatin1String("last_update"), QJsonValue::fromVariant(QVariant(it->getLastUpdate().toSecsSinceEpoch())));
                                                                                                                  ^~~~~~~~~~~~~~~~
                                                                                                                  toMSecsSinceEpoch
/Users/mahdiyartaheri/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h:254:12: note: 'toMSecsSinceEpoch' declared here
    qint64 toMSecsSinceEpoch() const;
           ^
/Users/mahdiyartaheri/Qt5.7.0/Projects/Viper-Browser/src/core/adblock/AdBlockManager.cpp:1018:115: error: no member named 'toSecsSinceEpoch' in 'QDateTime'; did you mean 'toMSecsSinceEpoch'?
        subscriptionObj.insert(QLatin1String("next_update"), QJsonValue::fromVariant(QVariant(it->getNextUpdate().toSecsSinceEpoch())));
                                                                                                                  ^~~~~~~~~~~~~~~~
                                                                                                                  toMSecsSinceEpoch
/Users/mahdiyartaheri/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h:254:12: note: 'toMSecsSinceEpoch' declared here
    qint64 toMSecsSinceEpoch() const;
           ^
5 errors generated.
make[2]: *** [src/core/CMakeFiles/viper-core.dir/adblock/AdBlockManager.cpp.o] Error 1
make[1]: *** [src/core/CMakeFiles/viper-core.dir/all] Error 2
make: *** [all] Error 2

**Comment by LeFroid** [comment]
I've modified that part of the AdBlockManager class to be compatibile with Qt versions < 5.8
I still recommend that you update to Qt 5.12.2, as QtWebEngine v5.7 is very likely to be using an insecure and unpatched version of Chromium

**Comment by LeFroid** [comment]
Closing the issue as this is an unsupported version of QtWebEngine and there has been no response from the reporter.
