### ISSUE TITLE
Does not run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [LeFroid/Viper-Browser#5]
Please compile on a build system no newer than the oldest currently still-supported LTS release, which is xenial at this time.
```
/run/firejail/appimage/.appimage-8495/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /run/firejail/appimage/.appimage-8495/AppRun)
/run/firejail/appimage/.appimage-8495/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.23' not found (required by /run/firejail/appimage/.appimage-8495/usr/bin/../lib/libQt5WebEngineCore.so.5)
/run/firejail/appimage/.appimage-8495/AppRun: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /run/firejail/appimage/.appimage-8495/usr/bin/../lib/libpng16.so.16)
```

References:
* https://github.com/AppImage/appimage.github.io/pull/1570
* https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

**Comment by LeFroid** [comment]
I've updated the Travis config to deploy an AppImage for each build, each of which are compiled on a Xenial distro.

Thank you for the bug report, and please let me know if you find any issues with the [latest build](https://github.com/LeFroid/Viper-Browser/releases/tag/continuous).

**Comment by probonopd** [comment]
Thank you very much 👍 
Added to https://appimage.github.io/Viper_Browser/
