### ISSUE TITLE
Preconfigure i-dont-care-about-cookies list

### ISSUE THREAD

**Issue by probonopd** [LeFroid/Viper-Browser#6]
It would be great if the [i-dont-care-about-cookies](https://www.i-dont-care-about-cookies.eu/) list would be enabled by default.

> Safari, Microsoft Edge and other browser users can install the filter list into their favorite ad blocker extension.

https://www.i-dont-care-about-cookies.eu/abp/

**Comment by LeFroid** [comment]
The current approach is that no ABP or uBO filter lists are to be downloaded without the user subscribing to them through the Ad-Blocking Management UI.

I've added this to the browser's Recommended Subscription List, and in the future will likely add a "Welcome" window that walks the user through choices like this before they start using the web browser.

**Comment by LeFroid** [comment]
Closing the issue since this has been marked as a recommended filter list & can easily be installed by the user.

**Comment by probonopd** [comment]
> a "Welcome" window that walks the user through choices like this

Good idea!
